### ISSUE TITLE
Cannot convert Celcius to canonical Form 

### ISSUE THREAD

**Issue by epicadk** [FHIR/Ucum-java#26]
Trying to run `getCanonicalForm()` on `100` `Cel` returns a null value with the code `K`

**Comment by michaelabuckley** [comment]
`[degF]` doesn't work either.

**Comment by grahamegrieve** [comment]
what would a test case look like?

**Comment by delcroip** [comment]
kg, years, day, month are working

**Comment by delcroip** [comment]
g/L and alike (mg/dL) and K are not working

**Comment by khyativyasargus** [comment]
[Test case Reference](https://github.com/google/android-fhir/issues/881#issuecomment-1628483946)

**Comment by grahamegrieve** [comment]
Added a test case that checks that this conversion fails with a UCUM exception. Actually supporting this test cases requires a total rework of the library architecture (offsets are supper painful)

**Comment by jingtang10** [comment]
@grahamegrieve is there a tracking issue for the work?

@khyativyasargus I think we can put in a workaround in the android fhir sdk repo for now until this is fixed/released in the ucum lib. I commented on the issue in the sdk repo.

**Comment by grahamegrieve** [comment]
> is there a tracking issue for the work?

no, because I'm not sure I'm going to do it. It's relatively easy to think that the library should be able to convert between F and C directly, but harder to figure out what to do in general. Consider say mm/C vs mm/F - that doesn't get an offset conversion. So what about C/mm vs F/mm - neither does that. but what about mm/C*2 convert to mm/F*2? Is that even a thing? I'm not sure. 

so maybe I could just write a special case just for F vs C?

**Comment by jingtang10** [comment]
i'm not great at physics, but i'd imagine when it comes to compound units it should be kelvin instead of C or F? I don't really understand mm/C or mm/F or C/mm or F/mm.

the original issue is about getting canonical form of C in K, because we do comparison in canonical units in the library. we don't really need F <-> C.
